name: CI/CD Pipeline for FastAPI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 登录 Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 构建并推送 Docker 镜像
      - name: Build and push Docker image
        run: |
          docker build -t gufengdong/my-fastapi-app:${{ github.sha }} .
          docker push gufengdong/my-fastapi-app:${{ github.sha }}

  deploy-to-kubernetes:
    needs: build-and-push  # 依赖构建任务
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'  # 仅在推送 main 分支时部署
    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      # 配置 Kubernetes 凭证
      - name: Configure Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

      # 部署到 Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/fastapi-app-deployment fastapi-app=gufengdong/my-fastapi-app:${{ github.sha }} -n default
          kubectl rollout status deployment/fastapi-app-deployment -n default